# Generated by Django 4.0.4 on 2022-05-10 05:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(countries_flag_url='//localhost:8000/{code}.png', blank=True, null=True),
        ),
    ]
